name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: yarn

            - run: yarn build

            - run: yarn test
